[package]
name = "bumaga"
version = "0.1.0"
edition = "2021"



[dependencies]
taffy = "0.5.1"
serde = "1.0"
serde_json = "1.0.118"
log = "0.4"
pest = { version = "2" }
pest_derive = { version = "2" }

