[package]
name = "macroquad-app"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
bumaga = { path = "../../" }
serde_json = "1.0"
env_logger = { version = "0.11", default-features = false }

[profile.release]
debug = 1