use crate::css::{ComputedValue, Dim, PropertyKey, Units};
use log::error;

pub fn initial(key: PropertyKey) -> ComputedValue {
    match key {
        PropertyKey::AccentColor => keyword("auto"),
        PropertyKey::AlignContent => keyword("normal"),
        PropertyKey::AlignItems => keyword("normal"),
        PropertyKey::AlignSelf => keyword("auto"),
        PropertyKey::AlignmentBaseline => keyword("auto"),
        PropertyKey::AnchorName => keyword("none"),
        PropertyKey::AnimationComposition => keyword("replace"),
        PropertyKey::AnimationDelay => s(0),
        PropertyKey::AnimationDirection => keyword("normal"),
        PropertyKey::AnimationDuration => s(0),
        PropertyKey::AnimationFillMode => keyword("none"),
        PropertyKey::AnimationIterationCount => n(1),
        PropertyKey::AnimationName => keyword("none"),
        PropertyKey::AnimationPlayState => keyword("running"),
        PropertyKey::AnimationRangeEnd => keyword("normal"),
        PropertyKey::AnimationRangeStart => keyword("normal"),
        PropertyKey::AnimationTimeline => keyword("auto"),
        PropertyKey::AnimationTimingFunction => keyword("ease"),
        PropertyKey::Appearance => keyword("none"),
        PropertyKey::AspectRatio => keyword("auto"),
        PropertyKey::BackfaceVisibility => keyword("visible"),
        PropertyKey::BackgroundAttachment => keyword("scroll"),
        PropertyKey::BackgroundBlendMode => keyword("normal"),
        PropertyKey::BackgroundClip => keyword("border-box"),
        PropertyKey::BackgroundColor => color(0, 0, 0, 0),
        PropertyKey::BackgroundImage => keyword("none"),
        PropertyKey::BackgroundOrigin => keyword("padding-box"),
        PropertyKey::BackgroundPositionX => percent(0.0),
        PropertyKey::BackgroundPositionY => percent(0.0),
        PropertyKey::BackgroundRepeat => keyword("repeat"),
        PropertyKey::BackgroundSize => keyword("auto"),
        PropertyKey::BorderBottomColor => keyword("currentColor"),
        PropertyKey::BorderBottomLeftRadius => zero(),
        PropertyKey::BorderBottomRightRadius => zero(),
        PropertyKey::BorderBottomStyle => keyword("none"),
        PropertyKey::BorderBottomWidth => keyword("medium"),
        PropertyKey::BorderCollapse => keyword("separate"),
        PropertyKey::BorderLeftColor => keyword("currentColor"),
        PropertyKey::BorderLeftStyle => keyword("none"),
        PropertyKey::BorderLeftWidth => keyword("medium"),
        PropertyKey::BorderRightColor => keyword("currentColor"),
        PropertyKey::BorderRightStyle => keyword("none"),
        PropertyKey::BorderRightWidth => keyword("medium"),
        PropertyKey::BorderSpacing => zero(),
        PropertyKey::BorderTopColor => keyword("currentColor"),
        PropertyKey::BorderTopLeftRadius => zero(),
        PropertyKey::BorderTopRightRadius => zero(),
        PropertyKey::BorderTopStyle => keyword("none"),
        PropertyKey::BorderTopWidth => keyword("medium"),
        PropertyKey::Bottom => keyword("auto"),
        PropertyKey::BoxShadow => keyword("none"),
        PropertyKey::BoxSizing => keyword("content-box"),
        PropertyKey::BreakAfter => keyword("auto"),
        PropertyKey::BreakBefore => keyword("auto"),
        PropertyKey::BreakInside => keyword("auto"),
        PropertyKey::CaptionSide => keyword("top"),
        PropertyKey::CaretColor => keyword("auto"),
        PropertyKey::Clear => keyword("none"),
        PropertyKey::ClipPath => keyword("none"),
        PropertyKey::Color => keyword("currentColor"),
        PropertyKey::ColorScheme => keyword("normal"),
        PropertyKey::ColumnCount => keyword("auto"),
        PropertyKey::ColumnFill => keyword("balance"),
        PropertyKey::ColumnGap => keyword("normal"),
        PropertyKey::ColumnRuleColor => keyword("currentColor"),
        PropertyKey::ColumnRuleStyle => keyword("none"),
        PropertyKey::ColumnRuleWidth => keyword("medium"),
        PropertyKey::ColumnSpan => keyword("none"),
        PropertyKey::ColumnWidth => keyword("auto"),
        PropertyKey::Contain => keyword("none"),
        PropertyKey::ContainIntrinsicBlockSize => keyword("none"),
        PropertyKey::ContainIntrinsicHeight => keyword("none"),
        PropertyKey::ContainIntrinsicInlineSize => keyword("none"),
        PropertyKey::ContainIntrinsicSize => keyword("none"),
        PropertyKey::ContainIntrinsicWidth => keyword("none"),
        PropertyKey::ContainerName => keyword("none"),
        PropertyKey::ContainerType => keyword("normal"),
        PropertyKey::Content => keyword("normal"),
        PropertyKey::ContentVisibility => keyword("visible"),
        PropertyKey::CounterIncrement => keyword("none"),
        PropertyKey::CounterReset => keyword("none"),
        PropertyKey::CounterSet => keyword("none"),
        PropertyKey::Cursor => keyword("auto"),
        PropertyKey::Direction => keyword("ltr"),
        PropertyKey::Display => keyword("block"),
        PropertyKey::DominantBaseline => keyword("auto"),
        PropertyKey::EmptyCells => keyword("show"),
        PropertyKey::FieldSizing => keyword("fixed"),
        PropertyKey::FillOpacity => n(1),
        PropertyKey::FillRule => keyword("nonzero"),
        PropertyKey::Filter => keyword("none"),
        PropertyKey::FlexBasis => keyword("auto"),
        PropertyKey::FlexDirection => keyword("row"),
        PropertyKey::FlexGrow => zero(),
        PropertyKey::FlexShrink => n(1),
        PropertyKey::FlexWrap => keyword("nowrap"),
        PropertyKey::Float => keyword("none"),
        PropertyKey::FontFamily => keyword("system-ui"),
        PropertyKey::FontFeatureSettings => keyword("normal"),
        PropertyKey::FontKerning => keyword("auto"),
        PropertyKey::FontLanguageOverride => keyword("normal"),
        PropertyKey::FontOpticalSizing => keyword("auto"),
        PropertyKey::FontPalette => keyword("normal"),
        PropertyKey::FontSize => px(16),
        PropertyKey::FontSizeAdjust => keyword("none"),
        PropertyKey::FontStretch => keyword("normal"),
        PropertyKey::FontStyle => keyword("normal"),
        PropertyKey::FontSynthesisPosition => keyword("none"),
        PropertyKey::FontSynthesisSmallCaps => keyword("auto"),
        PropertyKey::FontSynthesisStyle => keyword("auto"),
        PropertyKey::FontSynthesisWeight => keyword("auto"),
        PropertyKey::FontVariant => keyword("normal"),
        PropertyKey::FontVariantAlternates => keyword("normal"),
        PropertyKey::FontVariantCaps => keyword("normal"),
        PropertyKey::FontVariantEastAsian => keyword("normal"),
        PropertyKey::FontVariantEmoji => keyword("normal"),
        PropertyKey::FontVariantLigatures => keyword("normal"),
        PropertyKey::FontVariantNumeric => keyword("normal"),
        PropertyKey::FontVariantPosition => keyword("normal"),
        PropertyKey::FontVariationSettings => keyword("normal"),
        PropertyKey::FontWeight => keyword("normal"),
        PropertyKey::ForcedColorAdjust => keyword("auto"),
        PropertyKey::GridAutoColumns => keyword("auto"),
        PropertyKey::GridAutoFlow => keyword("row"),
        PropertyKey::GridAutoRows => keyword("auto"),
        PropertyKey::GridColumnEnd => keyword("auto"),
        PropertyKey::GridColumnStart => keyword("auto"),
        PropertyKey::GridRowEnd => keyword("auto"),
        PropertyKey::GridRowStart => keyword("auto"),
        PropertyKey::GridTemplateAreas => keyword("none"),
        PropertyKey::GridTemplateColumns => keyword("none"),
        PropertyKey::GridTemplateRows => keyword("none"),
        PropertyKey::HangingPunctuation => keyword("none"),
        PropertyKey::Height => keyword("auto"),
        PropertyKey::HyphenateCharacter => keyword("auto"),
        PropertyKey::HyphenateLimitChars => keyword("auto"),
        PropertyKey::Hyphens => keyword("manual"),
        PropertyKey::ImageOrientation => keyword("from-image"),
        PropertyKey::ImageRendering => keyword("auto"),
        PropertyKey::InitialLetter => keyword("normal"),
        PropertyKey::InlineSize => keyword("auto"),
        PropertyKey::InsetBlockEnd => keyword("auto"),
        PropertyKey::InsetBlockStart => keyword("auto"),
        PropertyKey::InsetInlineEnd => keyword("auto"),
        PropertyKey::InsetInlineStart => keyword("auto"),
        PropertyKey::Isolation => keyword("auto"),
        PropertyKey::JustifyContent => keyword("normal"),
        PropertyKey::JustifyItems => keyword("legacy"),
        PropertyKey::JustifySelf => keyword("auto"),
        PropertyKey::Left => keyword("auto"),
        PropertyKey::LetterSpacing => keyword("normal"),
        PropertyKey::LineBreak => keyword("auto"),
        PropertyKey::LineHeight => keyword("normal"),
        PropertyKey::LineHeightStep => zero(),
        PropertyKey::MarginBlockEnd => zero(),
        PropertyKey::MarginBlockStart => zero(),
        PropertyKey::MarginBottom => zero(),
        PropertyKey::MarginInlineEnd => zero(),
        PropertyKey::MarginInlineStart => zero(),
        PropertyKey::MarginLeft => zero(),
        PropertyKey::MarginRight => zero(),
        PropertyKey::MarginTop => zero(),
        PropertyKey::MarginTrim => keyword("none"),
        PropertyKey::MarkerEnd => keyword("none"),
        PropertyKey::MarkerMid => keyword("auto"),
        PropertyKey::MarkerStart => keyword("auto"),
        PropertyKey::MaskBorderMode => keyword("alpha"),
        PropertyKey::MaskBorderOutset => zero(),
        PropertyKey::MaskBorderRepeat => keyword("stretch"),
        PropertyKey::MaskBorderSlice => zero(),
        PropertyKey::MaskBorderSource => keyword("none"),
        PropertyKey::MaskBorderWidth => keyword("auto"),
        PropertyKey::MaskClip => keyword("border-box"),
        PropertyKey::MaskComposite => keyword("add"),
        PropertyKey::MaskImage => keyword("none"),
        PropertyKey::MaskMode => keyword("match-source"),
        PropertyKey::MaskOrigin => keyword("border-box"),
        PropertyKey::MaskRepeat => keyword("repeat"),
        PropertyKey::MaskSize => keyword("auto"),
        PropertyKey::MaskType => keyword("luminance"),
        PropertyKey::MaxBlockSize => keyword("none"),
        PropertyKey::MaxHeight => keyword("none"),
        PropertyKey::MaxInlineSize => keyword("none"),
        PropertyKey::MaxWidth => keyword("none"),
        PropertyKey::MinBlockSize => zero(),
        PropertyKey::MinHeight => keyword("auto"),
        PropertyKey::MinInlineSize => zero(),
        PropertyKey::MinWidth => keyword("auto"),
        PropertyKey::MixBlendMode => keyword("normal"),
        PropertyKey::ObjectFit => keyword("fill"),
        PropertyKey::OffsetAnchor => keyword("auto"),
        PropertyKey::OffsetDistance => zero(),
        PropertyKey::OffsetPath => keyword("none"),
        PropertyKey::OffsetPosition => keyword("normal"),
        PropertyKey::OffsetRotate => keyword("auto"),
        PropertyKey::Opacity => n(1),
        PropertyKey::Order => zero(),
        PropertyKey::Orphans => n(2),
        PropertyKey::OutlineColor => keyword("auto"),
        PropertyKey::OutlineOffset => zero(),
        PropertyKey::OutlineStyle => keyword("none"),
        PropertyKey::OutlineWidth => keyword("medium"),
        PropertyKey::OverflowAnchor => keyword("auto"),
        PropertyKey::OverflowBlock => keyword("auto"),
        PropertyKey::OverflowClipMargin => px(0),
        PropertyKey::OverflowInline => keyword("auto"),
        PropertyKey::OverflowWrap => keyword("normal"),
        PropertyKey::OverflowX => keyword("visible"),
        PropertyKey::OverflowY => keyword("visible"),
        PropertyKey::OverscrollBehavior => keyword("auto"),
        PropertyKey::OverscrollBehaviorBlock => keyword("auto"),
        PropertyKey::OverscrollBehaviorInline => keyword("auto"),
        PropertyKey::OverscrollBehaviorX => keyword("auto"),
        PropertyKey::OverscrollBehaviorY => keyword("auto"),
        PropertyKey::PaddingBlockEnd => zero(),
        PropertyKey::PaddingBlockStart => zero(),
        PropertyKey::PaddingBottom => zero(),
        PropertyKey::PaddingInlineEnd => zero(),
        PropertyKey::PaddingInlineStart => zero(),
        PropertyKey::PaddingLeft => zero(),
        PropertyKey::PaddingRight => zero(),
        PropertyKey::PaddingTop => zero(),
        PropertyKey::PageBreakAfter => keyword("auto"),
        PropertyKey::PageBreakBefore => keyword("auto"),
        PropertyKey::PageBreakInside => keyword("auto"),
        PropertyKey::Perspective => keyword("none"),
        PropertyKey::PointerEvents => keyword("auto"),
        PropertyKey::Position => keyword("static"),
        PropertyKey::PositionAnchor => keyword("implicit"),
        PropertyKey::PrintColorAdjust => keyword("economy"),
        PropertyKey::Resize => keyword("none"),
        PropertyKey::Right => keyword("auto"),
        PropertyKey::Rotate => keyword("none"),
        PropertyKey::RowGap => keyword("normal"),
        PropertyKey::RubyAlign => keyword("space-around"),
        PropertyKey::RubyPosition => keyword("alternate"),
        PropertyKey::Scale => keyword("none"),
        PropertyKey::ScrollBehavior => keyword("auto"),
        PropertyKey::ScrollMarginBlockEnd => zero(),
        PropertyKey::ScrollMarginBlockStart => zero(),
        PropertyKey::ScrollMarginBottom => zero(),
        PropertyKey::ScrollMarginInlineEnd => zero(),
        PropertyKey::ScrollMarginInlineStart => zero(),
        PropertyKey::ScrollMarginLeft => zero(),
        PropertyKey::ScrollMarginRight => zero(),
        PropertyKey::ScrollMarginTop => zero(),
        PropertyKey::ScrollPaddingBlockEnd => keyword("auto"),
        PropertyKey::ScrollPaddingBlockStart => keyword("auto"),
        PropertyKey::ScrollPaddingBottom => keyword("auto"),
        PropertyKey::ScrollPaddingInlineEnd => keyword("auto"),
        PropertyKey::ScrollPaddingInlineStart => keyword("auto"),
        PropertyKey::ScrollPaddingLeft => keyword("auto"),
        PropertyKey::ScrollPaddingRight => keyword("auto"),
        PropertyKey::ScrollPaddingTop => keyword("auto"),
        PropertyKey::ScrollSnapAlign => keyword("none"),
        PropertyKey::ScrollSnapStop => keyword("normal"),
        PropertyKey::ScrollSnapType => keyword("none"),
        PropertyKey::ScrollTimelineAxis => keyword("block"),
        PropertyKey::ScrollTimelineName => keyword("none"),
        PropertyKey::ScrollbarColor => keyword("auto"),
        PropertyKey::ScrollbarGutter => keyword("auto"),
        PropertyKey::ScrollbarWidth => keyword("auto"),
        PropertyKey::ShapeImageThreshold => n(0),
        PropertyKey::ShapeMargin => zero(),
        PropertyKey::ShapeOutside => keyword("none"),
        PropertyKey::TabSize => n(8),
        PropertyKey::TableLayout => keyword("auto"),
        PropertyKey::TextAlign => keyword("start"),
        PropertyKey::TextAlignLast => keyword("auto"),
        PropertyKey::TextCombineUpright => keyword("none"),
        PropertyKey::TextDecorationColor => keyword("currentColor"),
        PropertyKey::TextDecorationLine => keyword("none"),
        PropertyKey::TextDecorationSkip => keyword("objects"),
        PropertyKey::TextDecorationStyle => keyword("solid"),
        PropertyKey::TextDecorationThickness => keyword("auto"),
        PropertyKey::TextEmphasisColor => keyword("currentColor"),
        PropertyKey::TextEmphasisStyle => keyword("none"),
        PropertyKey::TextIndent => zero(),
        PropertyKey::TextJustify => keyword("auto"),
        PropertyKey::TextOrientation => keyword("mixed"),
        PropertyKey::TextOverflow => keyword("clip"),
        PropertyKey::TextShadow => keyword("none"),
        PropertyKey::TextSpacingTrim => keyword("normal"),
        PropertyKey::TextTransform => keyword("none"),
        PropertyKey::TextUnderlineOffset => keyword("auto"),
        PropertyKey::TextUnderlinePosition => keyword("auto"),
        PropertyKey::TextWrap => keyword("wrap"),
        PropertyKey::TextWrapMode => keyword("wrap"),
        PropertyKey::TextWrapStyle => keyword("auto"),
        PropertyKey::TimelineScope => keyword("none"),
        PropertyKey::Top => keyword("auto"),
        PropertyKey::TransformBox => keyword("view-box"),
        PropertyKey::TransformStyle => keyword("flat"),
        PropertyKey::Translate => keyword("none"),
        PropertyKey::UnicodeBidi => keyword("normal"),
        PropertyKey::UserSelect => keyword("auto"),
        PropertyKey::VerticalAlign => keyword("baseline"),
        PropertyKey::Visibility => keyword("visible"),
        PropertyKey::WhiteSpace => keyword("normal"),
        PropertyKey::WhiteSpaceCollapse => keyword("collapse"),
        PropertyKey::Widows => n(2),
        PropertyKey::Width => keyword("auto"),
        PropertyKey::WillChange => keyword("auto"),
        PropertyKey::WordBreak => keyword("normal"),
        PropertyKey::WordSpacing => keyword("normal"),
        PropertyKey::WritingMode => keyword("horizontal-tb"),
        PropertyKey::ZIndex => keyword("auto"),
        PropertyKey::Zoom => keyword("normal"),
        _ => {
            error!("there is no initial value for {key:?}");
            keyword("initial")
        }
    }
}

fn px(value: i32) -> ComputedValue {
    ComputedValue::Dimension(Dim::new(value as f32, Units::Px))
}

fn zero() -> ComputedValue {
    ComputedValue::Zero
}

#[inline(always)]
fn percent(value: f32) -> ComputedValue {
    ComputedValue::Percentage(value)
}

#[inline(always)]
fn color(r: u8, g: u8, b: u8, a: u8) -> ComputedValue {
    ComputedValue::Color([r, g, b, a])
}

#[inline(always)]
fn keyword(name: &str) -> ComputedValue {
    ComputedValue::Keyword(name.to_string())
}

#[inline(always)]
fn s(value: i32) -> ComputedValue {
    ComputedValue::Time(value as f32)
}

#[inline(always)]
fn n(value: i32) -> ComputedValue {
    ComputedValue::Number(value as f32)
}
