use log::{error, warn};
use std::collections::{BTreeMap, HashMap};

#[derive(Debug)]
pub struct Css {
    pub source: String,
    pub styles: Vec<Style>,
    pub animations: HashMap<String, Animation>,
}

#[derive(Debug, PartialEq)]
pub struct Animation {
    pub keyframes: Vec<Keyframe>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Keyframe {
    pub key: PropertyKey,
    pub frames: BTreeMap<u32, Vec<Shorthand>>,
}

/// A complex selector is a sequence of one or more simple and/or compound selectors that are
/// separated by combinators, including the white space descendant combinator.
#[derive(Debug, Clone)]
pub struct Complex {
    pub selectors: Vec<Simple>,
}

/// A simple selector with a single component, such as a single type selector,
/// attribute selector, or pseudo-class, that's not used in combination with or contains any other
/// selector component.
#[derive(Debug, Clone, PartialEq)]
pub enum Simple {
    All,
    Id(String),
    Class(String),
    Type(String),
    Attribute(String, Matcher, String),
    Root,
    PseudoClass(String),
    PseudoElement(String),
    Combinator(char),
}

/// Attribute selectors allow for more advanced matching
/// of substrings inside the value of your attribute.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Matcher {
    /// [attr]
    Exist,
    /// [attr=value]
    Equal,
    /// [attr~=value]
    Include,
    /// [attr|=value]
    DashMatch,
    /// [attr^=value]
    Prefix,
    /// [attr*=value]
    Substring,
    /// [attr$=value]
    Suffix,
}

impl Simple {
    pub fn as_combinator(&self) -> Option<char> {
        match self {
            Simple::Combinator(combinator) => Some(*combinator),
            _ => None,
        }
    }
}

#[derive(Debug, Clone)]
pub struct Style {
    /// A selector list is a comma-separated list of selectors.
    pub selectors: Vec<Complex>,
    pub declaration: Vec<Declaration>,
}

#[derive(Debug, Clone)]
pub enum Declaration {
    Variable(Variable),
    Property(Property),
}

#[derive(Debug, Clone)]
pub struct Variable {
    pub id: usize,
    pub key: String,
    pub values: Vec<Shorthand>,
}

/// A CSS property is a characteristic (like color) whose associated value
/// defines one aspect of how the application should display the element.
#[derive(Debug, Clone)]
pub struct Property {
    pub id: usize,
    pub key: PropertyKey,
    // TODO: global keywords: initial, inherit, unset
    // TODO: !important declaration
    pub values: Vec<Shorthand>,
}

pub type Shorthand = Vec<Definition>;

#[derive(Clone, Debug, PartialEq)]
pub enum Definition {
    Var(String),
    // TODO: any specific CSS function with custom syntax
    // CalcFunction(...)
    // CircleFunction(...)
    Function(Function),
    Explicit(ComputedValue),
}

// Explicitly specified in styles or as a result of computations.
#[derive(Clone, Debug, PartialEq)]
pub enum ComputedValue {
    Keyword(String),
    Zero,
    Percentage(f32),
    Time(f32),
    Dimension(Dim),
    Number(f32),
    Color([u8; 4]),
    String(String),
}

#[derive(Copy, Clone, Debug, PartialEq)]
pub struct Dim {
    pub value: f32,
    pub unit: Units,
}

impl Dim {
    pub fn new(value: f32, unit: Units) -> Self {
        Self { value, unit }
    }
}

#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Units {
    Vh,
    Vw,
    Vmax,
    Vmin,
    Px,
    Em,
    Rem,
}

impl Units {
    pub fn parse(name: &str) -> Option<Units> {
        let units = match name {
            "vh" => Units::Vh,
            "vw" => Units::Vw,
            "vmax" => Units::Vmax,
            "vmin" => Units::Vmin,
            "px" => Units::Px,
            "em" => Units::Em,
            "rem" => Units::Rem,
            _ => return None,
        };
        Some(units)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Function {
    pub name: String,
    pub arguments: Vec<Definition>,
}

impl Function {
    #[inline(always)]
    pub fn describe(&self) -> (&str, &[Definition]) {
        let name = self.name.as_str();
        let arguments = &self.arguments;
        (name, arguments)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Var {
    pub name: String,
    pub fallback: Option<String>,
}

/// based on https://www.w3.org/Style/CSS/all-properties.en.html
/// updated 2024-08-04
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PropertyKey {
    AccentColor,
    AlignContent,
    AlignItems,
    AlignSelf,
    AlignmentBaseline,
    All,
    AnchorName,
    AnchorScope,
    Animation,
    AnimationComposition,
    AnimationDelay,
    AnimationDirection,
    AnimationDuration,
    AnimationFillMode,
    AnimationIterationCount,
    AnimationName,
    AnimationPlayState,
    AnimationRange,
    AnimationRangeEnd,
    AnimationRangeStart,
    AnimationTimeline,
    AnimationTimingFunction,
    Appearance,
    AspectRatio,
    Azimuth,
    BackfaceVisibility,
    Background,
    BackgroundAttachment,
    BackgroundBlendMode,
    BackgroundClip,
    BackgroundColor,
    BackgroundImage,
    BackgroundOrigin,
    BackgroundPosition,
    BackgroundRepeat,
    BackgroundSize,
    BaselineShift,
    BaselineSource,
    BlockEllipsis,
    BlockSize,
    BlockStep,
    BlockStepAlign,
    BlockStepInsert,
    BlockStepRound,
    BlockStepSize,
    BookmarkLabel,
    BookmarkLevel,
    BookmarkState,
    Border,
    BorderBlock,
    BorderBlockColor,
    BorderBlockEnd,
    BorderBlockEndColor,
    BorderBlockEndStyle,
    BorderBlockEndWidth,
    BorderBlockStart,
    BorderBlockStartColor,
    BorderBlockStartStyle,
    BorderBlockStartWidth,
    BorderBlockStyle,
    BorderBlockWidth,
    BorderBottom,
    BorderBottomColor,
    BorderBottomLeftRadius,
    BorderBottomRightRadius,
    BorderBottomStyle,
    BorderBottomWidth,
    BorderBoundary,
    BorderCollapse,
    BorderColor,
    BorderEndEndRadius,
    BorderEndStartRadius,
    BorderImage,
    BorderImageOutset,
    BorderImageRepeat,
    BorderImageSlice,
    BorderImageSource,
    BorderImageWidth,
    BorderInline,
    BorderInlineColor,
    BorderInlineEnd,
    BorderInlineEndColor,
    BorderInlineEndStyle,
    BorderInlineEndWidth,
    BorderInlineStart,
    BorderInlineStartColor,
    BorderInlineStartStyle,
    BorderInlineStartWidth,
    BorderInlineStyle,
    BorderInlineWidth,
    BorderLeft,
    BorderLeftColor,
    BorderLeftStyle,
    BorderLeftWidth,
    BorderRadius,
    BorderRight,
    BorderRightColor,
    BorderRightStyle,
    BorderRightWidth,
    BorderSpacing,
    BorderStartEndRadius,
    BorderStartStartRadius,
    BorderStyle,
    BorderTop,
    BorderTopColor,
    BorderTopLeftRadius,
    BorderTopRightRadius,
    BorderTopStyle,
    BorderTopWidth,
    BorderWidth,
    Bottom,
    BoxDecorationBreak,
    BoxShadow,
    BoxSizing,
    BoxSnap,
    BreakAfter,
    BreakBefore,
    BreakInside,
    CaptionSide,
    Caret,
    CaretAnimation,
    CaretColor,
    CaretShape,
    Chains,
    Clear,
    Clip,
    ClipPath,
    ClipRule,
    Color,
    ColorAdjust,
    ColorInterpolationFilters,
    ColorScheme,
    ColumnCount,
    ColumnFill,
    ColumnGap,
    ColumnRule,
    ColumnRuleColor,
    ColumnRuleStyle,
    ColumnRuleWidth,
    ColumnSpan,
    ColumnWidth,
    Columns,
    Contain,
    ContainIntrinsicBlockSize,
    ContainIntrinsicHeight,
    ContainIntrinsicInlineSize,
    ContainIntrinsicSize,
    ContainIntrinsicWidth,
    Container,
    ContainerName,
    ContainerType,
    Content,
    ContentVisibility,
    Continue,
    CounterIncrement,
    CounterReset,
    CounterSet,
    Cue,
    CueAfter,
    CueBefore,
    Cursor,
    Direction,
    Display,
    DominantBaseline,
    Elevation,
    EmptyCells,
    FieldSizing,
    Fill,
    FillBreak,
    FillColor,
    FillImage,
    FillOpacity,
    FillOrigin,
    FillPosition,
    FillRepeat,
    FillRule,
    FillSize,
    Filter,
    Flex,
    FlexBasis,
    FlexDirection,
    FlexFlow,
    FlexGrow,
    FlexShrink,
    FlexWrap,
    Float,
    FloatDefer,
    FloatOffset,
    FloatReference,
    FloodColor,
    FloodOpacity,
    Flow,
    FlowFrom,
    FlowInto,
    Font,
    FontFamily,
    FontFeatureSettings,
    FontKerning,
    FontLanguageOverride,
    FontOpticalSizing,
    FontPalette,
    FontSize,
    FontSizeAdjust,
    FontStretch,
    FontStyle,
    FontSynthesis,
    FontSynthesisPosition,
    FontSynthesisSmallCaps,
    FontSynthesisStyle,
    FontSynthesisWeight,
    FontVariant,
    FontVariantAlternates,
    FontVariantCaps,
    FontVariantEastAsian,
    FontVariantEmoji,
    FontVariantLigatures,
    FontVariantNumeric,
    FontVariantPosition,
    FontVariationSettings,
    FontWeight,
    FontWidth,
    FootnoteDisplay,
    FootnotePolicy,
    ForcedColorAdjust,
    Gap,
    GlyphOrientationVertical,
    Grid,
    GridArea,
    GridAutoColumns,
    GridAutoFlow,
    GridAutoRows,
    GridColumn,
    GridColumnEnd,
    GridColumnStart,
    GridRow,
    GridRowEnd,
    GridRowStart,
    GridTemplate,
    GridTemplateAreas,
    GridTemplateColumns,
    GridTemplateRows,
    HangingPunctuation,
    Height,
    HyphenateCharacter,
    HyphenateLimitChars,
    HyphenateLimitLast,
    HyphenateLimitLines,
    HyphenateLimitZone,
    Hyphens,
    ImageOrientation,
    ImageRendering,
    ImageResolution,
    InitialLetter,
    InitialLetterAlign,
    InitialLetterWrap,
    InlineSize,
    InlineSizing,
    InputSecurity,
    Inset,
    InsetArea,
    InsetBlock,
    InsetBlockEnd,
    InsetBlockStart,
    InsetInline,
    InsetInlineEnd,
    InsetInlineStart,
    Isolation,
    JustifyContent,
    JustifyItems,
    JustifySelf,
    Left,
    LetterSpacing,
    LightingColor,
    LineBreak,
    LineClamp,
    LineFitEdge,
    LineGrid,
    LineHeight,
    LineHeightStep,
    LinePadding,
    LineSnap,
    ListStyle,
    ListStyleImage,
    ListStylePosition,
    ListStyleType,
    Margin,
    MarginBlock,
    MarginBlockEnd,
    MarginBlockStart,
    MarginBottom,
    MarginBreak,
    MarginInline,
    MarginInlineEnd,
    MarginInlineStart,
    MarginLeft,
    MarginRight,
    MarginTop,
    MarginTrim,
    Marker,
    MarkerEnd,
    MarkerKnockoutLeft,
    MarkerKnockoutRight,
    MarkerMid,
    MarkerPattern,
    MarkerSegment,
    MarkerSide,
    MarkerStart,
    Mask,
    MaskBorder,
    MaskBorderMode,
    MaskBorderOutset,
    MaskBorderRepeat,
    MaskBorderSlice,
    MaskBorderSource,
    MaskBorderWidth,
    MaskClip,
    MaskComposite,
    MaskImage,
    MaskMode,
    MaskOrigin,
    MaskPosition,
    MaskRepeat,
    MaskSize,
    MaskType,
    MaxBlockSize,
    MaxHeight,
    MaxInlineSize,
    MaxLines,
    MaxWidth,
    MinBlockSize,
    MinHeight,
    MinInlineSize,
    MinIntrinsicSizing,
    MinWidth,
    MixBlendMode,
    NavDown,
    NavLeft,
    NavRight,
    NavUp,
    ObjectFit,
    ObjectPosition,
    Offset,
    OffsetAnchor,
    OffsetDistance,
    OffsetPath,
    OffsetPosition,
    OffsetRotate,
    Opacity,
    Order,
    Orphans,
    Outline,
    OutlineColor,
    OutlineOffset,
    OutlineStyle,
    OutlineWidth,
    Overflow,
    OverflowAnchor,
    OverflowBlock,
    OverflowClipMargin,
    OverflowClipMarginBlock,
    OverflowClipMarginBlockEnd,
    OverflowClipMarginBlockStart,
    OverflowClipMarginBottom,
    OverflowClipMarginInline,
    OverflowClipMarginInlineEnd,
    OverflowClipMarginInlineStart,
    OverflowClipMarginLeft,
    OverflowClipMarginRight,
    OverflowClipMarginTop,
    OverflowInline,
    OverflowWrap,
    OverflowX,
    OverflowY,
    OverscrollBehavior,
    OverscrollBehaviorBlock,
    OverscrollBehaviorInline,
    OverscrollBehaviorX,
    OverscrollBehaviorY,
    Padding,
    PaddingBlock,
    PaddingBlockEnd,
    PaddingBlockStart,
    PaddingBottom,
    PaddingInline,
    PaddingInlineEnd,
    PaddingInlineStart,
    PaddingLeft,
    PaddingRight,
    PaddingTop,
    Page,
    PageBreakAfter,
    PageBreakBefore,
    PageBreakInside,
    Pause,
    PauseAfter,
    PauseBefore,
    Perspective,
    PerspectiveOrigin,
    Pitch,
    PitchRange,
    PlaceContent,
    PlaceItems,
    PlaceSelf,
    PlayDuring,
    PointerEvents,
    Position,
    PositionAnchor,
    PositionArea,
    PositionTry,
    PositionTryFallbacks,
    PositionTryOptions,
    PositionTryOrder,
    PositionVisibility,
    PrintColorAdjust,
    PropertyName,
    Quotes,
    RegionFragment,
    Resize,
    Rest,
    RestAfter,
    RestBefore,
    Richness,
    Right,
    Rotate,
    RowGap,
    RubyAlign,
    RubyMerge,
    RubyOverhang,
    RubyPosition,
    Running,
    Scale,
    ScrollBehavior,
    ScrollMargin,
    ScrollMarginBlock,
    ScrollMarginBlockEnd,
    ScrollMarginBlockStart,
    ScrollMarginBottom,
    ScrollMarginInline,
    ScrollMarginInlineEnd,
    ScrollMarginInlineStart,
    ScrollMarginLeft,
    ScrollMarginRight,
    ScrollMarginTop,
    ScrollPadding,
    ScrollPaddingBlock,
    ScrollPaddingBlockEnd,
    ScrollPaddingBlockStart,
    ScrollPaddingBottom,
    ScrollPaddingInline,
    ScrollPaddingInlineEnd,
    ScrollPaddingInlineStart,
    ScrollPaddingLeft,
    ScrollPaddingRight,
    ScrollPaddingTop,
    ScrollSnapAlign,
    ScrollSnapStop,
    ScrollSnapType,
    ScrollStartTarget,
    ScrollTimeline,
    ScrollTimelineAxis,
    ScrollTimelineName,
    ScrollbarColor,
    ScrollbarGutter,
    ScrollbarWidth,
    ShapeImageThreshold,
    ShapeInside,
    ShapeMargin,
    ShapeOutside,
    SpatialNavigationAction,
    SpatialNavigationContain,
    SpatialNavigationFunction,
    Speak,
    SpeakAs,
    SpeakHeader,
    SpeakNumeral,
    SpeakPunctuation,
    SpeechRate,
    Stress,
    StringSet,
    Stroke,
    StrokeAlign,
    StrokeAlignment,
    StrokeBreak,
    StrokeColor,
    StrokeDashCorner,
    StrokeDashJustify,
    StrokeDashadjust,
    StrokeDasharray,
    StrokeDashcorner,
    StrokeDashoffset,
    StrokeImage,
    StrokeLinecap,
    StrokeLinejoin,
    StrokeMiterlimit,
    StrokeOpacity,
    StrokeOrigin,
    StrokePosition,
    StrokeRepeat,
    StrokeSize,
    StrokeWidth,
    TabSize,
    TableLayout,
    TextAlign,
    TextAlignAll,
    TextAlignLast,
    TextAutospace,
    TextBox,
    TextBoxEdge,
    TextBoxTrim,
    TextCombineUpright,
    TextDecoration,
    TextDecorationColor,
    TextDecorationLine,
    TextDecorationSkip,
    TextDecorationSkipBox,
    TextDecorationSkipInk,
    TextDecorationSkipInset,
    TextDecorationSkipSelf,
    TextDecorationSkipSpaces,
    TextDecorationStyle,
    TextDecorationThickness,
    TextDecorationTrim,
    TextEmphasis,
    TextEmphasisColor,
    TextEmphasisPosition,
    TextEmphasisSkip,
    TextEmphasisStyle,
    TextGroupAlign,
    TextIndent,
    TextJustify,
    TextOrientation,
    TextOverflow,
    TextShadow,
    TextSpacing,
    TextSpacingTrim,
    TextTransform,
    TextUnderlineOffset,
    TextUnderlinePosition,
    TextWrap,
    TextWrapMode,
    TextWrapStyle,
    TimelineScope,
    Top,
    Transform,
    TransformBox,
    TransformOrigin,
    TransformStyle,
    Transition,
    TransitionBehavior,
    TransitionDelay,
    TransitionDuration,
    TransitionProperty,
    TransitionTimingFunction,
    Translate,
    UnicodeBidi,
    UserSelect,
    VerticalAlign,
    ViewTimeline,
    ViewTimelineAxis,
    ViewTimelineInset,
    ViewTimelineName,
    ViewTransitionClass,
    ViewTransitionName,
    Visibility,
    VoiceBalance,
    VoiceDuration,
    VoiceFamily,
    VoicePitch,
    VoiceRange,
    VoiceRate,
    VoiceStress,
    VoiceVolume,
    Volume,
    WhiteSpace,
    WhiteSpaceCollapse,
    WhiteSpaceTrim,
    Widows,
    Width,
    WillChange,
    WordBreak,
    WordSpaceTransform,
    WordSpacing,
    WordWrap,
    WrapAfter,
    WrapBefore,
    WrapFlow,
    WrapInside,
    WrapThrough,
    WritingMode,
    ZIndex,
    Zoom,
}

impl PropertyKey {
    pub fn parse(name: &str) -> Option<Self> {
        let key = match name {
            "accent-color" => Self::AccentColor,
            "align-content" => Self::AlignContent,
            "align-items" => Self::AlignItems,
            "align-self" => Self::AlignSelf,
            "alignment-baseline" => Self::AlignmentBaseline,
            "all" => Self::All,
            "anchor-name" => Self::AnchorName,
            "anchor-scope" => Self::AnchorScope,
            "animation" => Self::Animation,
            "animation-composition" => Self::AnimationComposition,
            "animation-delay" => Self::AnimationDelay,
            "animation-direction" => Self::AnimationDirection,
            "animation-duration" => Self::AnimationDuration,
            "animation-fill-mode" => Self::AnimationFillMode,
            "animation-iteration-count" => Self::AnimationIterationCount,
            "animation-name" => Self::AnimationName,
            "animation-play-state" => Self::AnimationPlayState,
            "animation-range" => Self::AnimationRange,
            "animation-range-end" => Self::AnimationRangeEnd,
            "animation-range-start" => Self::AnimationRangeStart,
            "animation-timeline" => Self::AnimationTimeline,
            "animation-timing-function" => Self::AnimationTimingFunction,
            "appearance" => Self::Appearance,
            "aspect-ratio" => Self::AspectRatio,
            "azimuth" => Self::Azimuth,
            "backface-visibility" => Self::BackfaceVisibility,
            "background" => Self::Background,
            "background-attachment" => Self::BackgroundAttachment,
            "background-blend-mode" => Self::BackgroundBlendMode,
            "background-clip" => Self::BackgroundClip,
            "background-color" => Self::BackgroundColor,
            "background-image" => Self::BackgroundImage,
            "background-origin" => Self::BackgroundOrigin,
            "background-position" => Self::BackgroundPosition,
            "background-repeat" => Self::BackgroundRepeat,
            "background-size" => Self::BackgroundSize,
            "baseline-shift" => Self::BaselineShift,
            "baseline-source" => Self::BaselineSource,
            "block-ellipsis" => Self::BlockEllipsis,
            "block-size" => Self::BlockSize,
            "block-step" => Self::BlockStep,
            "block-step-align" => Self::BlockStepAlign,
            "block-step-insert" => Self::BlockStepInsert,
            "block-step-round" => Self::BlockStepRound,
            "block-step-size" => Self::BlockStepSize,
            "bookmark-label" => Self::BookmarkLabel,
            "bookmark-level" => Self::BookmarkLevel,
            "bookmark-state" => Self::BookmarkState,
            "border" => Self::Border,
            "border-block" => Self::BorderBlock,
            "border-block-color" => Self::BorderBlockColor,
            "border-block-end" => Self::BorderBlockEnd,
            "border-block-end-color" => Self::BorderBlockEndColor,
            "border-block-end-style" => Self::BorderBlockEndStyle,
            "border-block-end-width" => Self::BorderBlockEndWidth,
            "border-block-start" => Self::BorderBlockStart,
            "border-block-start-color" => Self::BorderBlockStartColor,
            "border-block-start-style" => Self::BorderBlockStartStyle,
            "border-block-start-width" => Self::BorderBlockStartWidth,
            "border-block-style" => Self::BorderBlockStyle,
            "border-block-width" => Self::BorderBlockWidth,
            "border-bottom" => Self::BorderBottom,
            "border-bottom-color" => Self::BorderBottomColor,
            "border-bottom-left-radius" => Self::BorderBottomLeftRadius,
            "border-bottom-right-radius" => Self::BorderBottomRightRadius,
            "border-bottom-style" => Self::BorderBottomStyle,
            "border-bottom-width" => Self::BorderBottomWidth,
            "border-boundary" => Self::BorderBoundary,
            "border-collapse" => Self::BorderCollapse,
            "border-color" => Self::BorderColor,
            "border-end-end-radius" => Self::BorderEndEndRadius,
            "border-end-start-radius" => Self::BorderEndStartRadius,
            "border-image" => Self::BorderImage,
            "border-image-outset" => Self::BorderImageOutset,
            "border-image-repeat" => Self::BorderImageRepeat,
            "border-image-slice" => Self::BorderImageSlice,
            "border-image-source" => Self::BorderImageSource,
            "border-image-width" => Self::BorderImageWidth,
            "border-inline" => Self::BorderInline,
            "border-inline-color" => Self::BorderInlineColor,
            "border-inline-end" => Self::BorderInlineEnd,
            "border-inline-end-color" => Self::BorderInlineEndColor,
            "border-inline-end-style" => Self::BorderInlineEndStyle,
            "border-inline-end-width" => Self::BorderInlineEndWidth,
            "border-inline-start" => Self::BorderInlineStart,
            "border-inline-start-color" => Self::BorderInlineStartColor,
            "border-inline-start-style" => Self::BorderInlineStartStyle,
            "border-inline-start-width" => Self::BorderInlineStartWidth,
            "border-inline-style" => Self::BorderInlineStyle,
            "border-inline-width" => Self::BorderInlineWidth,
            "border-left" => Self::BorderLeft,
            "border-left-color" => Self::BorderLeftColor,
            "border-left-style" => Self::BorderLeftStyle,
            "border-left-width" => Self::BorderLeftWidth,
            "border-radius" => Self::BorderRadius,
            "border-right" => Self::BorderRight,
            "border-right-color" => Self::BorderRightColor,
            "border-right-style" => Self::BorderRightStyle,
            "border-right-width" => Self::BorderRightWidth,
            "border-spacing" => Self::BorderSpacing,
            "border-start-end-radius" => Self::BorderStartEndRadius,
            "border-start-start-radius" => Self::BorderStartStartRadius,
            "border-style" => Self::BorderStyle,
            "border-top" => Self::BorderTop,
            "border-top-color" => Self::BorderTopColor,
            "border-top-left-radius" => Self::BorderTopLeftRadius,
            "border-top-right-radius" => Self::BorderTopRightRadius,
            "border-top-style" => Self::BorderTopStyle,
            "border-top-width" => Self::BorderTopWidth,
            "border-width" => Self::BorderWidth,
            "bottom" => Self::Bottom,
            "box-decoration-break" => Self::BoxDecorationBreak,
            "box-shadow" => Self::BoxShadow,
            "box-sizing" => Self::BoxSizing,
            "box-snap" => Self::BoxSnap,
            "break-after" => Self::BreakAfter,
            "break-before" => Self::BreakBefore,
            "break-inside" => Self::BreakInside,
            "caption-side" => Self::CaptionSide,
            "caret" => Self::Caret,
            "caret-animation" => Self::CaretAnimation,
            "caret-color" => Self::CaretColor,
            "caret-shape" => Self::CaretShape,
            "chains" => Self::Chains,
            "clear" => Self::Clear,
            "clip" => Self::Clip,
            "clip-path" => Self::ClipPath,
            "clip-rule" => Self::ClipRule,
            "color" => Self::Color,
            "color-adjust" => Self::ColorAdjust,
            "color-interpolation-filters" => Self::ColorInterpolationFilters,
            "color-scheme" => Self::ColorScheme,
            "column-count" => Self::ColumnCount,
            "column-fill" => Self::ColumnFill,
            "column-gap" => Self::ColumnGap,
            "column-rule" => Self::ColumnRule,
            "column-rule-color" => Self::ColumnRuleColor,
            "column-rule-style" => Self::ColumnRuleStyle,
            "column-rule-width" => Self::ColumnRuleWidth,
            "column-span" => Self::ColumnSpan,
            "column-width" => Self::ColumnWidth,
            "columns" => Self::Columns,
            "contain" => Self::Contain,
            "contain-intrinsic-block-size" => Self::ContainIntrinsicBlockSize,
            "contain-intrinsic-height" => Self::ContainIntrinsicHeight,
            "contain-intrinsic-inline-size" => Self::ContainIntrinsicInlineSize,
            "contain-intrinsic-size" => Self::ContainIntrinsicSize,
            "contain-intrinsic-width" => Self::ContainIntrinsicWidth,
            "container" => Self::Container,
            "container-name" => Self::ContainerName,
            "container-type" => Self::ContainerType,
            "content" => Self::Content,
            "content-visibility" => Self::ContentVisibility,
            "continue" => Self::Continue,
            "counter-increment" => Self::CounterIncrement,
            "counter-reset" => Self::CounterReset,
            "counter-set" => Self::CounterSet,
            "cue" => Self::Cue,
            "cue-after" => Self::CueAfter,
            "cue-before" => Self::CueBefore,
            "cursor" => Self::Cursor,
            "direction" => Self::Direction,
            "display" => Self::Display,
            "dominant-baseline" => Self::DominantBaseline,
            "elevation" => Self::Elevation,
            "empty-cells" => Self::EmptyCells,
            "field-sizing" => Self::FieldSizing,
            "fill" => Self::Fill,
            "fill-break" => Self::FillBreak,
            "fill-color" => Self::FillColor,
            "fill-image" => Self::FillImage,
            "fill-opacity" => Self::FillOpacity,
            "fill-origin" => Self::FillOrigin,
            "fill-position" => Self::FillPosition,
            "fill-repeat" => Self::FillRepeat,
            "fill-rule" => Self::FillRule,
            "fill-size" => Self::FillSize,
            "filter" => Self::Filter,
            "flex" => Self::Flex,
            "flex-basis" => Self::FlexBasis,
            "flex-direction" => Self::FlexDirection,
            "flex-flow" => Self::FlexFlow,
            "flex-grow" => Self::FlexGrow,
            "flex-shrink" => Self::FlexShrink,
            "flex-wrap" => Self::FlexWrap,
            "float" => Self::Float,
            "float-defer" => Self::FloatDefer,
            "float-offset" => Self::FloatOffset,
            "float-reference" => Self::FloatReference,
            "flood-color" => Self::FloodColor,
            "flood-opacity" => Self::FloodOpacity,
            "flow" => Self::Flow,
            "flow-from" => Self::FlowFrom,
            "flow-into" => Self::FlowInto,
            "font" => Self::Font,
            "font-family" => Self::FontFamily,
            "font-feature-settings" => Self::FontFeatureSettings,
            "font-kerning" => Self::FontKerning,
            "font-language-override" => Self::FontLanguageOverride,
            "font-optical-sizing" => Self::FontOpticalSizing,
            "font-palette" => Self::FontPalette,
            "font-size" => Self::FontSize,
            "font-size-adjust" => Self::FontSizeAdjust,
            "font-stretch" => Self::FontStretch,
            "font-style" => Self::FontStyle,
            "font-synthesis" => Self::FontSynthesis,
            "font-synthesis-position" => Self::FontSynthesisPosition,
            "font-synthesis-small-caps" => Self::FontSynthesisSmallCaps,
            "font-synthesis-style" => Self::FontSynthesisStyle,
            "font-synthesis-weight" => Self::FontSynthesisWeight,
            "font-variant" => Self::FontVariant,
            "font-variant-alternates" => Self::FontVariantAlternates,
            "font-variant-caps" => Self::FontVariantCaps,
            "font-variant-east-asian" => Self::FontVariantEastAsian,
            "font-variant-emoji" => Self::FontVariantEmoji,
            "font-variant-ligatures" => Self::FontVariantLigatures,
            "font-variant-numeric" => Self::FontVariantNumeric,
            "font-variant-position" => Self::FontVariantPosition,
            "font-variation-settings" => Self::FontVariationSettings,
            "font-weight" => Self::FontWeight,
            "font-width" => Self::FontWidth,
            "footnote-display" => Self::FootnoteDisplay,
            "footnote-policy" => Self::FootnotePolicy,
            "forced-color-adjust" => Self::ForcedColorAdjust,
            "gap" => Self::Gap,
            "glyph-orientation-vertical" => Self::GlyphOrientationVertical,
            "grid" => Self::Grid,
            "grid-area" => Self::GridArea,
            "grid-auto-columns" => Self::GridAutoColumns,
            "grid-auto-flow" => Self::GridAutoFlow,
            "grid-auto-rows" => Self::GridAutoRows,
            "grid-column" => Self::GridColumn,
            "grid-column-end" => Self::GridColumnEnd,
            "grid-column-start" => Self::GridColumnStart,
            "grid-row" => Self::GridRow,
            "grid-row-end" => Self::GridRowEnd,
            "grid-row-start" => Self::GridRowStart,
            "grid-template" => Self::GridTemplate,
            "grid-template-areas" => Self::GridTemplateAreas,
            "grid-template-columns" => Self::GridTemplateColumns,
            "grid-template-rows" => Self::GridTemplateRows,
            "hanging-punctuation" => Self::HangingPunctuation,
            "height" => Self::Height,
            "hyphenate-character" => Self::HyphenateCharacter,
            "hyphenate-limit-chars" => Self::HyphenateLimitChars,
            "hyphenate-limit-last" => Self::HyphenateLimitLast,
            "hyphenate-limit-lines" => Self::HyphenateLimitLines,
            "hyphenate-limit-zone" => Self::HyphenateLimitZone,
            "hyphens" => Self::Hyphens,
            "image-orientation" => Self::ImageOrientation,
            "image-rendering" => Self::ImageRendering,
            "image-resolution" => Self::ImageResolution,
            "initial-letter" => Self::InitialLetter,
            "initial-letter-align" => Self::InitialLetterAlign,
            "initial-letter-wrap" => Self::InitialLetterWrap,
            "inline-size" => Self::InlineSize,
            "inline-sizing" => Self::InlineSizing,
            "input-security" => Self::InputSecurity,
            "inset" => Self::Inset,
            "inset-area" => Self::InsetArea,
            "inset-block" => Self::InsetBlock,
            "inset-block-end" => Self::InsetBlockEnd,
            "inset-block-start" => Self::InsetBlockStart,
            "inset-inline" => Self::InsetInline,
            "inset-inline-end" => Self::InsetInlineEnd,
            "inset-inline-start" => Self::InsetInlineStart,
            "isolation" => Self::Isolation,
            "justify-content" => Self::JustifyContent,
            "justify-items" => Self::JustifyItems,
            "justify-self" => Self::JustifySelf,
            "left" => Self::Left,
            "letter-spacing" => Self::LetterSpacing,
            "lighting-color" => Self::LightingColor,
            "line-break" => Self::LineBreak,
            "line-clamp" => Self::LineClamp,
            "line-fit-edge" => Self::LineFitEdge,
            "line-grid" => Self::LineGrid,
            "line-height" => Self::LineHeight,
            "line-height-step" => Self::LineHeightStep,
            "line-padding" => Self::LinePadding,
            "line-snap" => Self::LineSnap,
            "list-style" => Self::ListStyle,
            "list-style-image" => Self::ListStyleImage,
            "list-style-position" => Self::ListStylePosition,
            "list-style-type" => Self::ListStyleType,
            "margin" => Self::Margin,
            "margin-block" => Self::MarginBlock,
            "margin-block-end" => Self::MarginBlockEnd,
            "margin-block-start" => Self::MarginBlockStart,
            "margin-bottom" => Self::MarginBottom,
            "margin-break" => Self::MarginBreak,
            "margin-inline" => Self::MarginInline,
            "margin-inline-end" => Self::MarginInlineEnd,
            "margin-inline-start" => Self::MarginInlineStart,
            "margin-left" => Self::MarginLeft,
            "margin-right" => Self::MarginRight,
            "margin-top" => Self::MarginTop,
            "margin-trim" => Self::MarginTrim,
            "marker" => Self::Marker,
            "marker-end" => Self::MarkerEnd,
            "marker-knockout-left" => Self::MarkerKnockoutLeft,
            "marker-knockout-right" => Self::MarkerKnockoutRight,
            "marker-mid" => Self::MarkerMid,
            "marker-pattern" => Self::MarkerPattern,
            "marker-segment" => Self::MarkerSegment,
            "marker-side" => Self::MarkerSide,
            "marker-start" => Self::MarkerStart,
            "mask" => Self::Mask,
            "mask-border" => Self::MaskBorder,
            "mask-border-mode" => Self::MaskBorderMode,
            "mask-border-outset" => Self::MaskBorderOutset,
            "mask-border-repeat" => Self::MaskBorderRepeat,
            "mask-border-slice" => Self::MaskBorderSlice,
            "mask-border-source" => Self::MaskBorderSource,
            "mask-border-width" => Self::MaskBorderWidth,
            "mask-clip" => Self::MaskClip,
            "mask-composite" => Self::MaskComposite,
            "mask-image" => Self::MaskImage,
            "mask-mode" => Self::MaskMode,
            "mask-origin" => Self::MaskOrigin,
            "mask-position" => Self::MaskPosition,
            "mask-repeat" => Self::MaskRepeat,
            "mask-size" => Self::MaskSize,
            "mask-type" => Self::MaskType,
            "max-block-size" => Self::MaxBlockSize,
            "max-height" => Self::MaxHeight,
            "max-inline-size" => Self::MaxInlineSize,
            "max-lines" => Self::MaxLines,
            "max-width" => Self::MaxWidth,
            "min-block-size" => Self::MinBlockSize,
            "min-height" => Self::MinHeight,
            "min-inline-size" => Self::MinInlineSize,
            "min-intrinsic-sizing" => Self::MinIntrinsicSizing,
            "min-width" => Self::MinWidth,
            "mix-blend-mode" => Self::MixBlendMode,
            "nav-down" => Self::NavDown,
            "nav-left" => Self::NavLeft,
            "nav-right" => Self::NavRight,
            "nav-up" => Self::NavUp,
            "object-fit" => Self::ObjectFit,
            "object-position" => Self::ObjectPosition,
            "offset" => Self::Offset,
            "offset-anchor" => Self::OffsetAnchor,
            "offset-distance" => Self::OffsetDistance,
            "offset-path" => Self::OffsetPath,
            "offset-position" => Self::OffsetPosition,
            "offset-rotate" => Self::OffsetRotate,
            "opacity" => Self::Opacity,
            "order" => Self::Order,
            "orphans" => Self::Orphans,
            "outline" => Self::Outline,
            "outline-color" => Self::OutlineColor,
            "outline-offset" => Self::OutlineOffset,
            "outline-style" => Self::OutlineStyle,
            "outline-width" => Self::OutlineWidth,
            "overflow" => Self::Overflow,
            "overflow-anchor" => Self::OverflowAnchor,
            "overflow-block" => Self::OverflowBlock,
            "overflow-clip-margin" => Self::OverflowClipMargin,
            "overflow-clip-margin-block" => Self::OverflowClipMarginBlock,
            "overflow-clip-margin-block-end" => Self::OverflowClipMarginBlockEnd,
            "overflow-clip-margin-block-start" => Self::OverflowClipMarginBlockStart,
            "overflow-clip-margin-bottom" => Self::OverflowClipMarginBottom,
            "overflow-clip-margin-inline" => Self::OverflowClipMarginInline,
            "overflow-clip-margin-inline-end" => Self::OverflowClipMarginInlineEnd,
            "overflow-clip-margin-inline-start" => Self::OverflowClipMarginInlineStart,
            "overflow-clip-margin-left" => Self::OverflowClipMarginLeft,
            "overflow-clip-margin-right" => Self::OverflowClipMarginRight,
            "overflow-clip-margin-top" => Self::OverflowClipMarginTop,
            "overflow-inline" => Self::OverflowInline,
            "overflow-wrap" => Self::OverflowWrap,
            "overflow-x" => Self::OverflowX,
            "overflow-y" => Self::OverflowY,
            "overscroll-behavior" => Self::OverscrollBehavior,
            "overscroll-behavior-block" => Self::OverscrollBehaviorBlock,
            "overscroll-behavior-inline" => Self::OverscrollBehaviorInline,
            "overscroll-behavior-x" => Self::OverscrollBehaviorX,
            "overscroll-behavior-y" => Self::OverscrollBehaviorY,
            "padding" => Self::Padding,
            "padding-block" => Self::PaddingBlock,
            "padding-block-end" => Self::PaddingBlockEnd,
            "padding-block-start" => Self::PaddingBlockStart,
            "padding-bottom" => Self::PaddingBottom,
            "padding-inline" => Self::PaddingInline,
            "padding-inline-end" => Self::PaddingInlineEnd,
            "padding-inline-start" => Self::PaddingInlineStart,
            "padding-left" => Self::PaddingLeft,
            "padding-right" => Self::PaddingRight,
            "padding-top" => Self::PaddingTop,
            "page" => Self::Page,
            "page-break-after" => Self::PageBreakAfter,
            "page-break-before" => Self::PageBreakBefore,
            "page-break-inside" => Self::PageBreakInside,
            "pause" => Self::Pause,
            "pause-after" => Self::PauseAfter,
            "pause-before" => Self::PauseBefore,
            "perspective" => Self::Perspective,
            "perspective-origin" => Self::PerspectiveOrigin,
            "pitch" => Self::Pitch,
            "pitch-range" => Self::PitchRange,
            "place-content" => Self::PlaceContent,
            "place-items" => Self::PlaceItems,
            "place-self" => Self::PlaceSelf,
            "play-during" => Self::PlayDuring,
            "pointer-events" => Self::PointerEvents,
            "position" => Self::Position,
            "position-anchor" => Self::PositionAnchor,
            "position-area" => Self::PositionArea,
            "position-try" => Self::PositionTry,
            "position-try-fallbacks" => Self::PositionTryFallbacks,
            "position-try-options" => Self::PositionTryOptions,
            "position-try-order" => Self::PositionTryOrder,
            "position-visibility" => Self::PositionVisibility,
            "print-color-adjust" => Self::PrintColorAdjust,
            "property-name" => Self::PropertyName,
            "quotes" => Self::Quotes,
            "region-fragment" => Self::RegionFragment,
            "resize" => Self::Resize,
            "rest" => Self::Rest,
            "rest-after" => Self::RestAfter,
            "rest-before" => Self::RestBefore,
            "richness" => Self::Richness,
            "right" => Self::Right,
            "rotate" => Self::Rotate,
            "row-gap" => Self::RowGap,
            "ruby-align" => Self::RubyAlign,
            "ruby-merge" => Self::RubyMerge,
            "ruby-overhang" => Self::RubyOverhang,
            "ruby-position" => Self::RubyPosition,
            "running" => Self::Running,
            "scale" => Self::Scale,
            "scroll-behavior" => Self::ScrollBehavior,
            "scroll-margin" => Self::ScrollMargin,
            "scroll-margin-block" => Self::ScrollMarginBlock,
            "scroll-margin-block-end" => Self::ScrollMarginBlockEnd,
            "scroll-margin-block-start" => Self::ScrollMarginBlockStart,
            "scroll-margin-bottom" => Self::ScrollMarginBottom,
            "scroll-margin-inline" => Self::ScrollMarginInline,
            "scroll-margin-inline-end" => Self::ScrollMarginInlineEnd,
            "scroll-margin-inline-start" => Self::ScrollMarginInlineStart,
            "scroll-margin-left" => Self::ScrollMarginLeft,
            "scroll-margin-right" => Self::ScrollMarginRight,
            "scroll-margin-top" => Self::ScrollMarginTop,
            "scroll-padding" => Self::ScrollPadding,
            "scroll-padding-block" => Self::ScrollPaddingBlock,
            "scroll-padding-block-end" => Self::ScrollPaddingBlockEnd,
            "scroll-padding-block-start" => Self::ScrollPaddingBlockStart,
            "scroll-padding-bottom" => Self::ScrollPaddingBottom,
            "scroll-padding-inline" => Self::ScrollPaddingInline,
            "scroll-padding-inline-end" => Self::ScrollPaddingInlineEnd,
            "scroll-padding-inline-start" => Self::ScrollPaddingInlineStart,
            "scroll-padding-left" => Self::ScrollPaddingLeft,
            "scroll-padding-right" => Self::ScrollPaddingRight,
            "scroll-padding-top" => Self::ScrollPaddingTop,
            "scroll-snap-align" => Self::ScrollSnapAlign,
            "scroll-snap-stop" => Self::ScrollSnapStop,
            "scroll-snap-type" => Self::ScrollSnapType,
            "scroll-start-target" => Self::ScrollStartTarget,
            "scroll-timeline" => Self::ScrollTimeline,
            "scroll-timeline-axis" => Self::ScrollTimelineAxis,
            "scroll-timeline-name" => Self::ScrollTimelineName,
            "scrollbar-color" => Self::ScrollbarColor,
            "scrollbar-gutter" => Self::ScrollbarGutter,
            "scrollbar-width" => Self::ScrollbarWidth,
            "shape-image-threshold" => Self::ShapeImageThreshold,
            "shape-inside" => Self::ShapeInside,
            "shape-margin" => Self::ShapeMargin,
            "shape-outside" => Self::ShapeOutside,
            "spatial-navigation-action" => Self::SpatialNavigationAction,
            "spatial-navigation-contain" => Self::SpatialNavigationContain,
            "spatial-navigation-function" => Self::SpatialNavigationFunction,
            "speak" => Self::Speak,
            "speak-as" => Self::SpeakAs,
            "speak-header" => Self::SpeakHeader,
            "speak-numeral" => Self::SpeakNumeral,
            "speak-punctuation" => Self::SpeakPunctuation,
            "speech-rate" => Self::SpeechRate,
            "stress" => Self::Stress,
            "string-set" => Self::StringSet,
            "stroke" => Self::Stroke,
            "stroke-align" => Self::StrokeAlign,
            "stroke-alignment" => Self::StrokeAlignment,
            "stroke-break" => Self::StrokeBreak,
            "stroke-color" => Self::StrokeColor,
            "stroke-dash-corner" => Self::StrokeDashCorner,
            "stroke-dash-justify" => Self::StrokeDashJustify,
            "stroke-dashadjust" => Self::StrokeDashadjust,
            "stroke-dasharray" => Self::StrokeDasharray,
            "stroke-dashcorner" => Self::StrokeDashcorner,
            "stroke-dashoffset" => Self::StrokeDashoffset,
            "stroke-image" => Self::StrokeImage,
            "stroke-linecap" => Self::StrokeLinecap,
            "stroke-linejoin" => Self::StrokeLinejoin,
            "stroke-miterlimit" => Self::StrokeMiterlimit,
            "stroke-opacity" => Self::StrokeOpacity,
            "stroke-origin" => Self::StrokeOrigin,
            "stroke-position" => Self::StrokePosition,
            "stroke-repeat" => Self::StrokeRepeat,
            "stroke-size" => Self::StrokeSize,
            "stroke-width" => Self::StrokeWidth,
            "tab-size" => Self::TabSize,
            "table-layout" => Self::TableLayout,
            "text-align" => Self::TextAlign,
            "text-align-all" => Self::TextAlignAll,
            "text-align-last" => Self::TextAlignLast,
            "text-autospace" => Self::TextAutospace,
            "text-box" => Self::TextBox,
            "text-box-edge" => Self::TextBoxEdge,
            "text-box-trim" => Self::TextBoxTrim,
            "text-combine-upright" => Self::TextCombineUpright,
            "text-decoration" => Self::TextDecoration,
            "text-decoration-color" => Self::TextDecorationColor,
            "text-decoration-line" => Self::TextDecorationLine,
            "text-decoration-skip" => Self::TextDecorationSkip,
            "text-decoration-skip-box" => Self::TextDecorationSkipBox,
            "text-decoration-skip-ink" => Self::TextDecorationSkipInk,
            "text-decoration-skip-inset" => Self::TextDecorationSkipInset,
            "text-decoration-skip-self" => Self::TextDecorationSkipSelf,
            "text-decoration-skip-spaces" => Self::TextDecorationSkipSpaces,
            "text-decoration-style" => Self::TextDecorationStyle,
            "text-decoration-thickness" => Self::TextDecorationThickness,
            "text-decoration-trim" => Self::TextDecorationTrim,
            "text-emphasis" => Self::TextEmphasis,
            "text-emphasis-color" => Self::TextEmphasisColor,
            "text-emphasis-position" => Self::TextEmphasisPosition,
            "text-emphasis-skip" => Self::TextEmphasisSkip,
            "text-emphasis-style" => Self::TextEmphasisStyle,
            "text-group-align" => Self::TextGroupAlign,
            "text-indent" => Self::TextIndent,
            "text-justify" => Self::TextJustify,
            "text-orientation" => Self::TextOrientation,
            "text-overflow" => Self::TextOverflow,
            "text-shadow" => Self::TextShadow,
            "text-spacing" => Self::TextSpacing,
            "text-spacing-trim" => Self::TextSpacingTrim,
            "text-transform" => Self::TextTransform,
            "text-underline-offset" => Self::TextUnderlineOffset,
            "text-underline-position" => Self::TextUnderlinePosition,
            "text-wrap" => Self::TextWrap,
            "text-wrap-mode" => Self::TextWrapMode,
            "text-wrap-style" => Self::TextWrapStyle,
            "timeline-scope" => Self::TimelineScope,
            "top" => Self::Top,
            "transform" => Self::Transform,
            "transform-box" => Self::TransformBox,
            "transform-origin" => Self::TransformOrigin,
            "transform-style" => Self::TransformStyle,
            "transition" => Self::Transition,
            "transition-behavior" => Self::TransitionBehavior,
            "transition-delay" => Self::TransitionDelay,
            "transition-duration" => Self::TransitionDuration,
            "transition-property" => Self::TransitionProperty,
            "transition-timing-function" => Self::TransitionTimingFunction,
            "translate" => Self::Translate,
            "unicode-bidi" => Self::UnicodeBidi,
            "user-select" => Self::UserSelect,
            "vertical-align" => Self::VerticalAlign,
            "view-timeline" => Self::ViewTimeline,
            "view-timeline-axis" => Self::ViewTimelineAxis,
            "view-timeline-inset" => Self::ViewTimelineInset,
            "view-timeline-name" => Self::ViewTimelineName,
            "view-transition-class" => Self::ViewTransitionClass,
            "view-transition-name" => Self::ViewTransitionName,
            "visibility" => Self::Visibility,
            "voice-balance" => Self::VoiceBalance,
            "voice-duration" => Self::VoiceDuration,
            "voice-family" => Self::VoiceFamily,
            "voice-pitch" => Self::VoicePitch,
            "voice-range" => Self::VoiceRange,
            "voice-rate" => Self::VoiceRate,
            "voice-stress" => Self::VoiceStress,
            "voice-volume" => Self::VoiceVolume,
            "volume" => Self::Volume,
            "white-space" => Self::WhiteSpace,
            "white-space-collapse" => Self::WhiteSpaceCollapse,
            "white-space-trim" => Self::WhiteSpaceTrim,
            "widows" => Self::Widows,
            "width" => Self::Width,
            "will-change" => Self::WillChange,
            "word-break" => Self::WordBreak,
            "word-space-transform" => Self::WordSpaceTransform,
            "word-spacing" => Self::WordSpacing,
            "word-wrap" => Self::WordWrap,
            "wrap-after" => Self::WrapAfter,
            "wrap-before" => Self::WrapBefore,
            "wrap-flow" => Self::WrapFlow,
            "wrap-inside" => Self::WrapInside,
            "wrap-through" => Self::WrapThrough,
            "writing-mode" => Self::WritingMode,
            "z-index" => Self::ZIndex,
            "zoom" => Self::Zoom,
            _ => return None,
        };
        Some(key)
    }
}
